Проверка паспортов: {
    externalEntity: ИС МВД РФ
    dataStore: Черные списки паспортов
    dataStore.shape: Parallelogram
    process: Распаковка архива, поиск дублей и некачественных данных
    process.shape: Circle

    externalEntity -> process: https/bzip2
    process -> dataStore: pgsql/сырые данные
    dataStore -> process: pgsql/обработанные данные
}

Карточка ФЛ {
    process1: Обработка черных списков, поиск по базе ФЛ и смена KYC-статуса
    process1.shape: Circle
    process2: Ручное изменение Карточки ФЛ через UI
    process2.shape: Circle
    process3: Поиск Карточки ФЛ по запросу
    process3.shape: Circle
    dataStore: Карточка ФЛ с KYC-статусами
    dataStore.shape: Parallelogram

    process3 -> dataStore: pgsql/Карточка ФЛ
    process2 -> dataStore: pgsql/Карточка ФЛ
    process1 -> dataStore: pgsql/обновление KYC-статуса
    dataStore -> process1: pgsql/Карточка ФЛ
}

Карточка ЮЛ {
    process1: Обновление Карточек ЮЛ и смена KYC-статуса
    process1.shape: Circle
    process2: Поиск Карточки ЮЛ по запросу
    process2.shape: Circle
    dataStore: Карточка ЮЛ с KYC-статусами
    dataStore.shape: Parallelogram

    process1 -> dataStore: pgsql/Карточка ЮЛ
    process2 -> dataStore: pgsql/Карточка ЮЛ
}

Каталог бизнес-событий {
    externalEntity: Каталог бизнес-событий
    dataStore: Хранилище событий
    dataStore.shape: Parallelogram

    externalEntity -> dataStore
    dataStore -> externalEntity
}

Платформа данных {
    externalEntity: Платформа данных
    dataStore1: Слой хранения данных
    dataStore1.shape: Parallelogram
    dataStore2: Витрины представлений
    dataStore2.shape: Parallelogram
    dataStore3: Кеш витрин данных
    dataStore3.shape: Parallelogram

    externalEntity -> dataStore1: arenadatadb
    dataStore1 -> dataStore2: arenadatadb
    dataStore2 -> dataStore3: pgsql
    dataStore3 -> externalEntity: pgsql
}

Связи ЮЛ {
    dataStore: Связи участников ЮЛ
    dataStore.shape: Parallelogram
    process1: Обновление графа ЮЛ
    process1.shape: Circle
    process2: Обработка черных списков, поиск по графу ЮЛ
    process2.shape: Circle
    process3: Обработка документов с участниками ЮЛ из открытых источников
    process3.shape: Circle
    process4: Построение вероятностных связей ML на данных с других источников
    process4.shape: Circle
    process5: Ручное создание связей через UI
    process5.shape: Circle
    process6: Подготовка черного списка ЮЛ
    process6.shape: Circle

    process1 -> dataStore: arangodb/Карточки ФЛ
    process2 -> dataStore: arangodb/обновление связи
    process3 -> dataStore: arangodb/обновление связи
    process4 -> dataStore: arangodb/обновление связи
    process5 -> dataStore: arangodb/обновление связи
    process6 -> dataStore: arangodb/обновление связи
}

Системы-потребители {
    Касса
    Платежный модуль
    Кредитный модуль
    Мобильный банк
    Интернет-банк
}

Проверка паспортов.process -> Платформа данных.externalEntity: kafka/стрим изменений модели данных черных списков паспортов
Проверка паспортов.process -> Каталог бизнес-событий.externalEntity: artemismq/событие изменения черных списков паспортов

Каталог бизнес-событий.externalEntity -> Карточка ФЛ.process1: artemismq/обновление черных списков
Платформа данных.externalEntity -> Карточка ФЛ.process1: pgsql/черные списки паспортов
Карточка ФЛ.process1 -> Платформа данных.externalEntity: kafka/обновленные Карточки ФЛ
Карточка ФЛ.process1 -> Каталог бизнес-событий.externalEntity: artemismq/событие обновления Карточек ФЛ

Каталог бизнес-событий.externalEntity -> Связи ЮЛ.process2: artemismq/обновление черных списков
Платформа данных.externalEntity -> Связи ЮЛ.process2: pgsql/черные списки паспортов
Связи ЮЛ.process6 -> Платформа данных.externalEntity: kafka/обновленные Связи ЮЛ
Связи ЮЛ.process6 -> Каталог бизнес-событий.externalEntity: artemismq/событие обновления Связей ЮЛ

Связи ЮЛ.process1 -> Карточка ЮЛ.process1: kafka/плоские списки ЮЛ
Карточка ЮЛ.process1 -> Связи ЮЛ.process1: kafka/Карточки ЮЛ
Карточка ЮЛ.process1 -> Платформа данных.externalEntity: kafka/обновленные Карточек ЮЛ
Карточка ЮЛ.process1 -> Каталог бизнес-событий.externalEntity: artemismq/событие обновления Карточек ЮЛ

Системы-потребители -> Карточка ЮЛ.process2 : rest/запрос на поиск Карточки ЮЛ существующего клиента (для синхронных процессов имеющихся клиентов)
Системы-потребители -> Карточка ФЛ.process3 : rest/запрос на поиск Карточки ФЛ существующего клиента (для синхронных процессов имеющихся клиентов)
Каталог бизнес-событий.externalEntity -> Системы-потребители: artemismq/события-уведомления обновлений черных списков паспортов для побуждения к действию (обновление локального кеша списков или запуска бизнес-процессов маркировки клиентов в запущенных процессах)
Каталог бизнес-событий.externalEntity -> Системы-потребители: artemismq/события-уведомления обновлений Карточек ФЛ для побуждения к действию (обновление локального кеша списков или запуска бизнес-процессов маркировки клиентов в запущенных процессах)
Каталог бизнес-событий.externalEntity -> Системы-потребители: artemismq/события-уведомления обновлений Карточек ЮЛ для побуждения к действию (обновление локального кеша списков или запуска бизнес-процессов маркировки клиентов в запущенных процессах)
Каталог бизнес-событий.externalEntity -> Системы-потребители: artemismq/события-уведомления обновлений Связей ЮЛ для побуждения к действию (обновление локального кеша списков или запуска бизнес-процессов маркировки клиентов в запущенных процессах)
Платформа данных.externalEntity -> Системы-потребители: pgsql/чтение витрины черных списков паспортов для наполнения собственного кеш-хранилища потребителей
Платформа данных.externalEntity -> Системы-потребители: pgsql/чтение витрины Карточек ФЛ для наполнения собственного кеш-хранилища потребителей 
Платформа данных.externalEntity -> Системы-потребители: pgsql/чтение витрины Карточек ЮЛ для наполнения собственного кеш-хранилища потребителей
Платформа данных.externalEntity -> Системы-потребители: pgsql/прямые запросы поиска по витрине как дата-продукту для конкретного потребителя для поиска по черным спискам паспортов в синхронных процессах для новых клиентов
Платформа данных.externalEntity -> Системы-потребители: pgsql/прямые запросы поиска по витрине как дата-продукту для конкретного потребителя для поиска по Карточкам ЮЛ в синхронных процессах для существующих клиентов
Платформа данных.externalEntity -> Системы-потребители: pgsql/прямые запросы поиска по витрине как дата-продукту для конкретного потребителя для поиска по Карточкам ФЛ в синхронных процессах для существующих клиентов
Карточка ФЛ.process1 -> Системы-потребители: kafka/события потока изменений модели данных Карточки ФЛ для наполнения собственного кеш-хранилища потребителей без использования Платформы данных и систему уведомлений Каталога бизнес-событий
Карточка ЮЛ.process1 -> Системы-потребители: kafka/события потока изменений модели данных Карточки ЮЛ для наполнения собственного кеш-хранилища потребителей без использования Платформы данных и систему уведомлений Каталога бизнес-событий
